#!/bin/bash
#PBS  -N secofs_nc_00
#PBS  -A ESTOFS-DEV
#PBS  -q dev
#PBS  -o /lfs/h1/nos/ptmp/mansur.jisan/rpt/v3.7.0/secofs_nc_00.out
#PBS  -e /lfs/h1/nos/ptmp/mansur.jisan/rpt/v3.7.0/secofs_nc_00.err
#PBS  -l place=vscatter:excl,select=24:ncpus=128:mpiprocs=120
#PBS  -l walltime=01:30:00

. /lfs/h1/nos/estofs/noscrub/$LOGNAME/packages/nosofs.v3.7.0/versions/run.ver

# Working directory
RPTDIR=/lfs/h1/nos/ptmp/$LOGNAME/rpt/v3.7.0
WORKDIR=/lfs/h1/nos/ptmp/$LOGNAME/work/${nosofs_ver}/secofs
if [ ! -r $WORKDIR ]; then
  mkdir -p -m 755 $WORKDIR
fi
cd ${WORKDIR}

# Module setup
module purge
module load envvar/${envvars_ver}
module load PrgEnv-intel/${PrgEnv_intel_ver}
module load craype/${craype_ver}
module load intel/${intel_ver}
module load cray-mpich/${cray_mpich_ver}
module load cray-pals/${cray_pals_ver}
module load netcdf/${netcdf_ver}
module load hdf5/${hdf5_ver}
module load libjpeg/${libjpeg_ver}
module load subversion/${subversion_ver}
module load python/${python_ver}
module load prod_envir/${prod_envir_ver}
module load prod_util/${prod_util_ver}
module load grib_util/${grib_util_ver}
module load cfp/${cfp_ver}
module load gsl/${gsl_ver}
module load udunits/${udunits_ver}
module load nco/${nco_ver}
module load cdo/${cdo_ver}
module load metis/${metis_ver}

module list

# EXPORT list
set +x
export envir=dev
export OFS=secofs
export cyc=00
export job=secofs_nc_00_$envir
export platform=ptmp

export KEEPDATA=YES
export SENDCOM=NO
export SENDDBN=NO
export SENDSMS=NO

export nosofs_ver=v3.7.0
export PACKAGEROOT=/lfs/h1/nos/estofs/noscrub/$LOGNAME/packages

# Data and COM paths
export COMPATH=/lfs/h1/ops/prod/com/nos
export COMROOT=/lfs/h1/nos/ptmp/$LOGNAME/com
export DCOMROOT=/lfs/h1/ops/prod/dcom
export DATAROOT=/lfs/h1/nos/ptmp/$LOGNAME/work/${nosofs_ver}/${OFS}
export COMIN=/lfs/h1/ops/prod/com

# Input data paths (production WCOSS2)
export COMINnam=/lfs/h1/ops/prod/com/nam/${nam_ver}
export COMINhrrr=/lfs/h1/ops/prod/com/hrrr/${hrrr_ver}
export COMINrap=/lfs/h1/ops/prod/com/rap/${rap_ver}
export COMINgfs=/lfs/h1/ops/prod/com/gfs/${gfs_ver}
export COMINrtma=/lfs/h1/ops/prod/com/rtma/${rtma_ver}
export COMINetss=/lfs/h1/ops/prod/com/petss/${petss_ver}
export COMINrtofs_2d=/lfs/h1/ops/prod/com/rtofs/${rtofs_ver}
export COMINrtofs_3d=/lfs/h1/ops/prod/com/rtofs/${rtofs_ver}
export COMINnwm=/lfs/h1/ops/prod/com/nwm/${nwm_ver}

################################################
# CALL executable job script here
export pbsid=${PBS_JOBID%%.*}
export job=${job:-$PBS_JOBNAME}
export jobid=${jobid:-$job.$PBS_JOBID}

# YAML configuration
export OFS_CONFIG=/lfs/h1/nos/estofs/noscrub/$LOGNAME/packages/nosofs.v3.7.0/parm/systems/secofs.yaml
export PYTHONPATH=/lfs/h1/nos/estofs/noscrub/$LOGNAME/packages/nosofs.v3.7.0/ush/python:${PYTHONPATH:-}

/lfs/h1/nos/estofs/noscrub/$LOGNAME/packages/nosofs.${nosofs_ver}/jobs/JNOS_OFS_NOWCAST
