!--------------------------------------------------------------------------
!
!  Program Name: nos_ofs_reformat_ROMS_CTL.f
!
!  Contact: NOS/CO-OPS Aijun Zhang
!           Phone: 240-533-0591   Email: aijun.zhang@noaa.gov
!
!  Abstract:  This program is to reformat ROMS-based model input file
!
!  History Log:
!           03/29/2019
!  Usage:
!
!    nos_ofs_reformat_ROMS_CTL < reformat_ROMS_CTL.ctl
!    Where the control file reformat_ROMS_CTL.ctl is generated by
!    script nos_ofs_prep_roms_ctl.sh


cccccccccccc Machuan Peng made some changes according to ROMS new version 3.6
cccccccccc they need LBC input variables which has two lines in tracers case

       parameter(NREC=10000)
       CHARACTER*200 FIN,ROMS_CTL,FOUT,BUFFER,VNAME*30
       CHARACTER*200 CROMS(NREC),CINP(NREC),CTMP,CTMP1,CMD
       READ(5,'(a)')FIN
       READ(5,'(a)')ROMS_CTL
       READ(5,'(a)')FOUT
       
       OPEN(10,file=TRIM(ROMS_CTL) )
       OPEN(11,file=TRIM(FIN) )
       OPEN(12,file=TRIM(FOUT) )
       I=1
       DO
10      READ(10,'(a)',END=20)BUFFER
!        CROMS(I)=TRIM(ADJUSTL(BUFFER))
        CROMS(I)=TRIM(BUFFER)
        I=I+1       
       ENDDO

20     CONTINUE
       NLROMS=I-1
       PRINT *,'Number of total lines of ',TRIM(ROMS_CTL),NLROMS
    
       I=1
       DO
30      READ(11,'(a)',END=50)BUFFER
        CINP(I)=TRIM(ADJUSTL(BUFFER))
        I=I+1       
       ENDDO
50     CONTINUE
       NINP=I-1
       PRINT *,'Number of total lines in original roms.in',NINP
       
       DO N=1,NLROMS
!          BUFFER=TRIM(ADJUSTL(CROMS(N)))
          BUFFER=TRIM(CROMS(N))
          ILEN=len_trim(ADJUSTL(BUFFER))
	  IF((ILEN .LE. 0) .OR. (BUFFER(1:1) .EQ. '!')) THEN
             WRITE(12,'(a)')trim(BUFFER)
          ELSE
             INX=INDEX(BUFFER,'=')
	     IF(INX .LE. 0)THEN
               WRITE(12,'(a)')trim(BUFFER)
             ELSE  
              VNAME=ADJUSTL(BUFFER(1:INX-1))
	      IF (TRIM(VNAME) .NE. 'FRCNAME' )THEN
               DO I=1,NINP
	         CTMP1=TRIM(ADJUSTL(CINP(I)))
                 CTMP='  '
                 INX=INDEX(CTMP1,'=')
                 CTMP=CTMP1(1:INX-1)
	         IF(TRIM(CTMP) .EQ. TRIM(VNAME) )THEN
	           CTMP1='     '//TRIM(CTMP1)
                   WRITE(12,'(a)')TRIM(CTMP1)
		   GOTO 80
		 ENDIF  
	       ENDDO
               WRITE(12,'(a)')'     '//TRIM(BUFFER)

	      ELSEIF(TRIM(VNAME) .EQ. 'FRCNAME' )THEN
               IEXIST=-1
               DO I=1,NINP
	         CTMP1=TRIM(ADJUSTL(CINP(I)))
                 CTMP='  '
                 INX=INDEX(CTMP1,'=')
                 CTMP=CTMP1(1:INX-1)
	         IF(TRIM(CTMP) .EQ. 'NFFILES' )THEN
                    INX=INDEX(CTMP1,'=',BACK=.TRUE.)
		    READ(CTMP1(INX+1:INX+3),'(I3)')NFFILES
                    IEXIST=1
		    EXIT
		 ENDIF
	       ENDDO
               IF (IEXIST .LE. 0)THEN
	        WRITE(*,*)'NFFILES is not found'
	        WRITE(*,*)'FRCNAME and NFFILES have to be specified'
	        STOP
               ENDIF
60	       CONTINUE	 
               DO I=1,NINP
	         CTMP1=TRIM(ADJUSTL(CINP(I)))
                 CTMP='  '
                 INX=INDEX(CTMP1,'=')
                 CTMP=CTMP1(1:INX-1)
	         IF(TRIM(CTMP) .EQ. TRIM(VNAME) )EXIT
	       ENDDO
70	       CONTINUE
               I0=I
	       DO K=1,NFFILES
                 I=I0+K-1
	         CTMP1='     '//TRIM(ADJUSTL(CINP(I)))
                 WRITE(12,'(a)')TRIM(CTMP1)
	       ENDDO 
	      ENDIF    	 
	     ENDIF
          ENDIF 
80        CONTINUE	                        
	ENDDO   
        CLOSE(10)
        CLOSE(11)  
        CLOSE(12)  

       OPEN(10,file=TRIM(FOUT) )
       OPEN(11,file='tmp_ctl.ctl' )
       I=1
       CTMP='tmpppp'
       DO
         READ(10,'(a)',end=820)BUFFER
         ILEN=len_trim(ADJUSTL(BUFFER))
         IF((ILEN .LE. 0) .OR. (BUFFER(1:1) .EQ. '!')) THEN
             WRITE(11,'(a)')trim(BUFFER)
             CTMP=BUFFER
         ELSE
           IF(TRIM(ADJUSTL(CTMP)) .NE. TRIM(ADJUSTL(BUFFER)) )THEN
             WRITE(11,'(a)')TRIM(BUFFER)
             CTMP=BUFFER
           ENDIF
         ENDIF
       ENDDO
820    continue
       CLOSE(10)
       CLOSE(11)
       CMD='mv '//TRIM(FOUT)//'  '// TRIM(FOUT)//'.old'
!       write(*,*)trim(CMD)
       call system(trim(CMD))
       CMD='mv tmp_ctl.ctl'//'  '// TRIM(FOUT)
!       write(*,*)trim(CMD)
       call system(trim(CMD))
       STOP
       END
